import { withMermaid } from "vitepress-plugin-mermaid";

// https://vitepress.dev/reference/site-config
export default withMermaid({
  title: "cc-analyzer",
  description:
    "Read-only CLI to browse and analyze Claude Code sessions in ~/.claude — cost, tokens, tools, skills, models, and per-turn breakdowns.",
  base: "/cc-analyzer/",
  lastUpdated: true,
  cleanUrls: true,

  head: [["link", { rel: "icon", href: "/cc-analyzer/favicon.svg" }]],

  themeConfig: {
    nav: [
      { text: "Home", link: "/" },
      { text: "Docs", link: "/docs/" },
    ],

    sidebar: {
      "/docs/": [
        {
          text: "Overview",
          items: [{ text: "Home", link: "/docs/" }],
        },
        {
          text: "Reference",
          items: [
            { text: "1. Repository Structure", link: "/docs/1-repository-structure" },
            {
              text: "2. Core Analysis Engine",
              link: "/docs/2-core-analysis-engine",
              collapsed: false,
              items: [
                {
                  text: "2.1 Parsing & Events",
                  link: "/docs/2-1-session-parsing-and-events",
                },
                { text: "2.2 Cost & Pricing", link: "/docs/2-2-cost-and-pricing" },
                { text: "2.3 Index & Analytics", link: "/docs/2-3-index-and-analytics" },
              ],
            },
            { text: "3. Command-Line Interface", link: "/docs/3-cli" },
            { text: "4. Interactive Terminal UI", link: "/docs/4-tui" },
            { text: "5. Web Server & API", link: "/docs/5-web-server-and-api" },
            { text: "6. Web SPA Frontend", link: "/docs/6-web-spa-frontend" },
            { text: "Glossary", link: "/docs/glossary" },
          ],
        },
      ],
    },

    search: { provider: "local" },

    socialLinks: [{ icon: "github", link: "https://github.com/yorch/cc-analyzer" }],

    editLink: {
      pattern: "https://github.com/yorch/cc-analyzer/edit/main/wiki/:path",
      text: "Edit the source wiki page",
    },

    footer: {
      message: "Read-only · never writes to ~/.claude",
      copyright:
        'Docs generated by <a href="https://github.com/yorch/cc-analyzer">repo-wiki-generator</a>',
    },
  },
});
