import { withMermaid } from "vitepress-plugin-mermaid";

// https://vitepress.dev/reference/site-config
export default withMermaid({
  title: "cc-analyzer",
  description:
    "Read-only CLI to browse and analyze Claude Code sessions in ~/.claude — cost, tokens, tools, skills, models, and per-turn breakdowns.",
  base: "/cc-analyzer/",
  lastUpdated: true,
  cleanUrls: true,
  // The whole aesthetic is an amber-phosphor CRT; dark is the intended default,
  // with the light "print-out" theme still one toggle away.
  appearance: "dark",

  head: [["link", { rel: "icon", href: "/cc-analyzer/favicon.svg" }]],

  // Light-mode ("print-out") diagram palette: warm-cream nodes, amber-ink
  // borders, monospace labels. Dark mode uses mermaid's built-in dark theme
  // (forced by the plugin); the light-tuned vars below leak into it, so the
  // dark plate + amber node/edge tints are repainted in the site's custom CSS.
  mermaid: {
    theme: "base",
    themeVariables: {
      fontFamily: '"IBM Plex Mono", ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
      fontSize: "14px",
      primaryColor: "#f7efdc",
      primaryBorderColor: "#9a5f12",
      primaryTextColor: "#3a2c14",
      secondaryColor: "#efe4c9",
      secondaryBorderColor: "#8a5410",
      tertiaryColor: "#f3ead4",
      tertiaryBorderColor: "rgba(120,84,24,0.4)",
      lineColor: "#927a49",
      clusterBkg: "#f3ead4",
      clusterBorder: "rgba(120,84,24,0.4)",
      edgeLabelBackground: "#f3ead4",
    },
  },

  themeConfig: {
    nav: [
      { text: "Home", link: "/" },
      { text: "Install", link: "/install" },
      { text: "Docs", link: "/docs/" },
    ],

    sidebar: {
      "/docs/": [
        {
          text: "Overview",
          items: [{ text: "Home", link: "/docs/" }],
        },
        {
          text: "Reference",
          items: [
            { text: "1. Repository Structure", link: "/docs/1-repository-structure" },
            {
              text: "2. Core Analysis Engine",
              link: "/docs/2-core-analysis-engine",
              collapsed: false,
              items: [
                {
                  text: "2.1 Parsing & Events",
                  link: "/docs/2-1-session-parsing-and-events",
                },
                { text: "2.2 Cost & Pricing", link: "/docs/2-2-cost-and-pricing" },
                { text: "2.3 Index & Aggregation", link: "/docs/2-3-index-and-analytics" },
                { text: "2.4 Per-Turn Steps", link: "/docs/2-4-per-turn-steps" },
              ],
            },
            { text: "3. Command-Line Interface", link: "/docs/3-cli" },
            { text: "4. Interactive Terminal UI", link: "/docs/4-tui" },
            { text: "5. Web Server & API", link: "/docs/5-web-server-and-api" },
            { text: "6. Web SPA Frontend", link: "/docs/6-web-spa-frontend" },
            { text: "7. Analytics & Insights", link: "/docs/7-analytics-and-insights" },
            { text: "8. Updates & Distribution", link: "/docs/8-updates-and-distribution" },
            { text: "9. Docs Site", link: "/docs/9-docs-site" },
            { text: "Glossary", link: "/docs/glossary" },
          ],
        },
      ],
    },

    search: { provider: "local" },

    socialLinks: [{ icon: "github", link: "https://github.com/yorch/cc-analyzer" }],

    editLink: {
      pattern: "https://github.com/yorch/cc-analyzer/edit/main/wiki/:path",
      text: "Edit the source wiki page",
    },

    footer: {
      message: "◍ read-only · local · never writes to ~/.claude",
      copyright:
        'Docs generated by <a href="https://github.com/yorch/claude-skills/tree/main/skills/repo-wiki-generator">repo-wiki-generator</a>',
    },
  },
});
