#!/usr/bin/env bun
/**
 * Sync the canonical wiki (../wiki) into the VitePress docs section (../docs).
 *
 * The wiki under /wiki is the single source of truth (regenerated by the
 * repo-wiki-generator skill). This script copies it into site/docs/ with two
 * transforms so it routes cleanly in VitePress:
 *   1. README.md -> index.md          (the docs-section home)
 *   2. dotted prefixes 2.1- -> 2-1-   (dots make fragile VitePress routes)
 * and rewrites intra-wiki links to match. The DeepWiki page headers and the
 * absolute GitHub citation URLs are left intact.
 */
import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const wikiDir = join(here, "..", "..", "wiki");
const docsDir = join(here, "..", "docs");

/** Skip meta files; VitePress nav is defined in .vitepress/config.ts. */
const SKIP = new Set(["_meta.json", "_SIDEBAR.md"]);

/** Map a wiki filename to its docs filename. */
function targetName(name: string): string {
  if (name === "README.md") return "index.md";
  // 2.1-foo.md -> 2-1-foo.md
  return name.replace(/^(\d+)\.(\d+)-/, "$1-$2-");
}

/** Rewrite relative intra-wiki links to match the renamed targets. */
function rewriteLinks(content: string): string {
  return content
    .replace(/\(\.\/README\.md/g, "(./index.md")
    .replace(/\(\.\/(\d+)\.(\d+)-/g, "(./$1-$2-");
}

async function main() {
  const entries = await readdir(wikiDir);
  const mdFiles = entries.filter((f) => f.endsWith(".md") && !SKIP.has(f));
  if (mdFiles.length === 0) throw new Error(`No wiki pages found in ${wikiDir}`);

  await rm(docsDir, { recursive: true, force: true });
  await mkdir(docsDir, { recursive: true });

  for (const file of mdFiles) {
    const raw = await Bun.file(join(wikiDir, file)).text();
    await writeFile(join(docsDir, targetName(file)), rewriteLinks(raw));
  }

  console.log(`Synced ${mdFiles.length} wiki pages -> site/docs/`);
}

await main();
