#!/usr/bin/env bun
// Reads the single-file Vite build (web/dist/index.html) and writes it into
// src/web/spa.ts as an embedded string, so `bun build --compile` bakes the
// whole web UI into the binary.
import { fileURLToPath } from "node:url";

const htmlPath = fileURLToPath(new URL("../web/dist/index.html", import.meta.url));
const outPath = fileURLToPath(new URL("../src/web/spa.ts", import.meta.url));

const htmlFile = Bun.file(htmlPath);
if (!(await htmlFile.exists())) {
  console.error(`Build output not found at ${htmlPath}. Run \`vite build\` first.`);
  process.exit(1);
}

const html = await htmlFile.text();
const module = `// GENERATED by scripts/embed-spa.ts — do not edit by hand.
export const spaHtml = ${JSON.stringify(html)};
export const hasSpa = true;
`;
await Bun.write(outPath, module);
console.log(`Embedded ${(html.length / 1024).toFixed(0)} KB SPA into src/web/spa.ts`);
