// This file is regenerated by `scripts/embed-spa.ts` from the Vite build output
// (web/dist/index.html). The committed placeholder lets the server compile
// before the SPA is built; `bun run build:web` fills in the real HTML.
export const spaHtml = "";
export const hasSpa = false;
